### ISSUE TITLE
Private mode

### ISSUE THREAD

**Issue by justarandomuser** [X3n0m0rph59/eruption#88]
**Introduction**
Request for mode/feature that does inspect OS processes and other information which could be considered as sensitive.

**Describe The Problem To Be Solved**
As a user, I'd like a mode of eruption that removes/disables the ability for it to collect any information about what I'm running. Essentially a 'private' mode.

**Describe the Solution**
Adding a button/toggle that disables the collection of any telemetry from my PC. This in turn disables certain modes that rely on capturing the data that would otherwise be collected.
Alternatively, would it be possible to have an option to select exactly what sort of information can be used. For example, I do not want process information used but I do want screen information.

**Comment by X3n0m0rph59** [comment]
Hi @justarandomuser, thank you for your request.

Eruption does not store any sensitive data by default and does not 'phone home' in any way. Only under the following circumstances will Eruption store certain usage information:

* If you remove the comment sign / enable the `stats.lua` script in a `.profile` file, Eruption will store a counter (a histogram) of how many times each key has been pressed, in the `/var/lib/eruption` directory. This is currently used by the `heatmap.profile` and `heatmap-errors.profile` to color each key depending on usage frequency.
This feature is disabled in the default installation.

Other privacy sensitive behavior:

* The `eruption-process-monitor` daemon listens on a Linux netlink socket and processes Linux kernel events related to process creation. Additionally it has multiple ways to query the properties of the currently active Window on X11 and Wayland. Introspection of process memory is currently not implemented.

You can disable processing of kernel process events and window notifications at any time by running:
```sh
$ systemctl --user disable --now eruption-process-monitor.service
```

This will disable the automatic profile switching mechanism since the `eruption-process-monitor` can't instruct the Eruption daemon to switch profiles anymore.

* The ambient effect transfers the contents of the screen encoded in the NetFX protocol. You can check whether the ambient effect may be running by searching for a running `eruption-netfx .* ambient` process.

It is currently not planned to add some kind of 'privacy mode button' since we simply can not verify or guarantee that a user-installed 3rd party Lua script does not store sensitive information.

Additionally, you can configure the sensors built into the `eruption-process-monitor` daemon via certain build flags.

**Comment by justarandomuser** [comment]
Hi @X3n0m0rph59 

Thanks for your well thought out response. I will close this out as it looks like you've covered everything.
Might I suggest adding this content to the readme as it may interest others too.

Regards,
